-- phpMyAdmin SQL Dump
-- version 4.4.14
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: Dec 31, 2015 at 06:59 PM
-- Server version: 5.6.26
-- PHP Version: 5.6.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `sig_indonesia`
--

-- --------------------------------------------------------

--
-- Table structure for table `data`
--

CREATE TABLE IF NOT EXISTS `data` (
  `id` int(11) NOT NULL,
  `point_start` double NOT NULL,
  `point_end` double NOT NULL,
  `title` varchar(100) NOT NULL,
  `description` text NOT NULL,
  `icon` varchar(100) NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=72 DEFAULT CHARSET=latin1;

--
-- Dumping data for table `data`
--

INSERT INTO `data` (`id`, `point_start`, `point_end`, `title`, `description`, `icon`) VALUES
(1, 5.5611863, 95.2936829, 'Banda Aceh', 'Kota Banda Aceh adalah salah satu kota yang berada di Aceh dan menjadi ibu kota Provinsi Aceh, Indonesia. Banda Aceh merupakan kota Islam yang paling tua di Asia Tenggara, di mana Kota Banda Aceh merupakan ibu kota dari Kesultanan Aceh. Jumlah Penduduk Aceh 223.446 jiwa.', 'http://localhost:8080/sig_indonesia/img/marker-blue.png'),
(2, 3.6426183, 98.5294062, 'Medan', 'Medan adalah Ibukota provinsi Sumatera Utara. Medan adalah kota terbesar keempat di Indonesia. Medan telah dijuluki oleh Belanda sebagai Parijs van Soematra karena kemiripannya dengan Paris selama era pendudukan Belanda. Jumlah penduduknya sekitar 2.185.789 jiwa.', 'http://localhost:8080/sig_indonesia/img/marker-blue.png'),
(3, -0.9402105, 100.3912699, 'Padang', 'Ibu Kota Provinsi Sumatera Barat', 'http://localhost:8080/sig_indonesia/img/marker-blue.png'),
(4, 0.5137912, 101.441176, 'Pekanbaru', 'Pekanbaru adalah ibukota Riau, di pulau Sumatera. memiliki luas wilayah 632,26 km² dengan populasi 950.571, sehingga menjadikan kota ini sebagai kota terbesar keempat di Sumatera, setelah Medan. Kota ini terletak di tepi Sungai Siak, yang mengalir ke Selat Malaka.', 'http://localhost:8080/sig_indonesia/img/marker-blue.png'),
(5, -1.7525658, 101.6687826, 'Jambi', 'Jambi terletak di pantai timur Sumatera. Provinsi ini memiliki lahan seluas 50,058.16 km persegi.', 'http://localhost:8080/sig_indonesia/img/marker-blue.png'),
(6, -2.9549663, 104.6927519, 'Palembang', 'Palembang adalah kota terbesar kedua di pulau Sumatera setelah Medan. Ini adalah salah satu kota tertua di Kepulauan Melayu dan Asia Tenggara. Palembang terletak di Sungai Musi di pantai timur Sumatera Selatan, dengan luas tanah 374,03 kilometer persegi dan berpenduduk 1.742.186 orang (2013 perkiraan). Palembang adalah kota terbesar ketujuh di Indonesia setelah Jakarta, Surabaya, Bandung, Medan, Semarang dan Makassar.', 'http://localhost:8080/sig_indonesia/img/marker-blue.png'),
(7, -3.8925232, 100.1542343, 'Bengkulu', 'Bengkulu adalah provinsi dari Indonesia. Terletak di pantai barat daya Sumatera, berbatasan provinsi Sumatera Barat, Jambi, Sumatera Selatan dan Lampung. Provinsi ini juga mencakup Pulau Enggano. Ibukota dan kota terbesar adalah kota Bengkulu.Kota ini dulunya adalah tempat sebuah garnisun Inggris, yang mereka sebut Bencoolen.', 'http://localhost:8080/sig_indonesia/img/marker-blue.png'),
(8, -5.4285635, 105.1309958, 'Bandar Lampung', 'Kota Bandar Lampung adalah sebuah kota di Indonesia sekaligus ibu kota dan kota terbesar di provinsi Lampung. Bandar Lampung juga merupakan kota terbesar ketiga di Pulau Sumatera setelah Medan dan Palembang menurut jumlah penduduk. Kota Bandar Lampung memiliki luas wilayah daratan 169,21 km² yang terbagi ke dalam 20 Kecamatan dan 126 Kelurahan dengan populasi penduduk 1.167.101 jiwa (berdasarkan data tahun 2014)', 'http://localhost:8080/sig_indonesia/img/marker-blue.png'),
(9, -2.1159932, 106.0506583, 'Pangkal Pinang', 'Pangkalpinang adalah salah satu Daerah Pemerintahan Kota di Indonesia yang merupakan bagian dari Provinsi Kepulauan Bangka Belitung sekaligus merupakan ibu kota Provinsi. Kota ini terletak di bagian timur Pulau Bangka. Memiliki wilayah seluas 118,408 km2 dan jumlah penduduk berdasarkan Sensus Penduduk 2010 sebanyak 328,167 jiwa', 'http://localhost:8080/sig_indonesia/img/marker-blue.png'),
(10, 0.9171049, 104.4670448, 'Tanjung Pinang', 'Tanjungpinang atau sebelumnya disebut Tanjung Pinang (disingkat Tg. Pinang) adalah ibu kota Kepulauan Riau, Indonesia. Yang terletak di koordinat 0º5 lintang utara dan 104º27 bujur timur, tepatnya di Pulau Bintan.', 'http://localhost:8080/sig_indonesia/img/marker-blue.png'),
(11, -6.2293867, 106.6894309, 'Jakarta', 'Daerah Khusus Ibukota Jakarta (DKI Jakarta) adalah ibu kota negara Indonesia. Jakarta merupakan satu-satunya kota di Indonesia yang memiliki status setingkat provinsi. Jakarta terletak di Tatar Pasundan, bagian barat laut Pulau Jawa. Jakarta memiliki luas sekitar 661,52 km² (lautan: 6.977,5 km²), dengan penduduk berjumlah 10.187.595 jiwa (2011).', 'http://localhost:8080/sig_indonesia/img/marker-blue.png'),
(12, -7.803164, 110.3398253, 'Yogyakarta', ' Daerah Istimewa Yogyakarta terletak di bagian selatan Pulau Jawa, dan berbatasan dengan Provinsi Jawa Tengah dan Samudera Hindia. Memiliki luas 3.185,80 km2 ini terdiri atas satu kotamadya, dan empat kabupaten, yang terbagi lagi menjadi 78 kecamatan, dan 438 desa/kelurahan. Menurut sensus penduduk 2010 memiliki populasi 3.452.390 jiwa dengan proporsi 1.705.404 laki-laki, dan 1.746.986 perempuan, serta memiliki kepadatan penduduk sebesar 1.084 jiwa per km2.', 'http://localhost:8080/sig_indonesia/img/marker-blue.png'),
(13, -6.9032739, 107.5731169, 'Bandung', 'Kota Bandung merupakan kota metropolitan terbesar di Provinsi Jawa Barat, sekaligus menjadi ibu kota provinsi tersebut. Kota ini terletak 140 km sebelah tenggara Jakarta, dan merupakan kota terbesar ketiga di Indonesia setelah Jakarta dan Surabaya menurut jumlah penduduk. Selain itu, Kota Bandung juga merupakan kota terbesar di wilayah Pulau Jawa bagian selatan. Sedangkan wilayah Bandung Raya (Wilayah Metropolitan Bandung) merupakan metropolitan terbesar ketiga di Indonesia setelah Jabodetabek dan Gerbangkertosusila (Gerbangkertosusilo). Kota kembang merupakan sebutan lain untuk kota ini, karena pada zaman dulu kota ini dinilai sangat cantik dengan banyaknya pohon-pohon dan bunga-bunga yang tumbuh di sana. Selain itu Bandung dahulunya disebut juga dengan Parijs van Java karena keindahannya. Luas wilayah kota Bandung yaitu 167.7 km persegi dan jumlah penduduknya sekitar 2.395.000 juta jiwa (2010)', 'http://localhost:8080/sig_indonesia/img/marker-blue.png'),
(14, -7.0245998, 110.3488076, 'Semarang', 'Kota Semarang adalah ibukota Provinsi Jawa Tengah, Indonesia sekaligus kota metropolitan terbesar kelima di Indonesia sesudah Jakarta, Surabaya, Bandung, dan Medan. Sebagai salah satu kota paling berkembang di Pulau Jawa, Kota Semarang mempunyai jumlah penduduk yang hampir mencapai 2 juta jiwa dan siang hari bisa mencapai 2,5 juta jiwa.', 'http://localhost:8080/sig_indonesia/img/marker-blue.png'),
(15, -7.2754438, 112.6416437, 'Surabaya', 'Kota Surabaya adalah ibu kota Provinsi Jawa Timur, Indonesia sekaligus menjadi kota metropolitan terbesar di provinsi tersebut. Surabaya merupakan kota terbesar kedua di Indonesia setelah Jakarta. Surabaya memiliki luas sekitar 333,063 km² dengan penduduknya berjumlah 2.909.257 jiwa (2015).', 'http://localhost:8080/sig_indonesia/img/marker-blue.png'),
(16, -6.1106106, 106.1415103, 'Serang', 'Kota Serang adalah ibu kota Provinsi Banten, Indonesia. Kota ini berada di bagian utara Provinsi Banten, serta dikelilingi oleh Kabupaten Serang di sebelah selatan, barat, dan timur, dan Laut Jawa di sebelah utara. Kota Serang dilintasi jalan tol lintas Jakarta-Merak. dengan Luas Wilayah 267 km² dan jumlah penduduk 643,101 jiwa (2010)', 'http://localhost:8080/sig_indonesia/img/marker-blue.png'),
(17, -8.6725072, 115.1542221, 'Denpasar', 'Kota Denpasar adalah ibu kota Provinsi Bali, Indonesia. Sementara luas wilayah Kota Denpasar 127,78 km² atau 2,18% dari luas wilayah Provinsi Bali. dan jumlah pendudukny sekitar 788,589 jiwa (2010)', 'http://localhost:8080/sig_indonesia/img/marker-blue.png'),
(18, -10.1748647, 123.5796988, 'Kupang', 'Kota Kupang adalah sebuah kotamadya dan sekaligus ibu kota provinsi Nusa Tenggara Timur, Indonesia. Kotamadya ini adalah kota yang terbesar di Pulau Timor yang terletak di pesisir Teluk Kupang, bagian barat laut pulau Timor. Luas wilayah Kota Kupang adalah 180,27 km² dengan jumlah penduduk sekitar 450.360 jiwa (2014). Daerah ini terbagi menjadi 6 kecamatan dan 51 kelurahan.', 'http://localhost:8080/sig_indonesia/img/marker-blue.png'),
(19, -8.5876173, 116.0815805, 'Mataram', 'Kota Mataram merupakan ibukota Provinsi Nusa Tenggara Barat, Indonesia. Adat Sasak dan Adat Bali cukup mewarnai masyarakat di kota ini. jumlah penduduk sekitar 402,843 jiwa (2010). dan luas wilayah 61.3 km²', 'http://localhost:8080/sig_indonesia/img/marker-blue.png'),
(20, -0.0353948, 109.2616819, 'Pontianak', 'Kota Pontianak adalah ibukota provinsi Kalimantan Barat, Indonesia. Kota ini dikenal sebagai Kota Khatulistiwa karena dilalui garis khatulistiwa. Di utara kota ini, tepatnya Siantan, terdapat Tugu Khatulistiwa yang dibangun pada tempat yang dilalui garis khatulistiwa. Selain itu, Kota Pontianak juga dilalui Sungai Kapuas, sungai terpanjang di Indonesia dan Sungai Landak. Sungai Kapuas dan Sungai Landak yang membelah kota menjadi simbol di dalam logo Kota Pontianak. Kota ini memiliki luas wilayah 107,82 kilometer persegi.', 'http://localhost:8080/sig_indonesia/img/marker-blue.png'),
(21, -2.2097007, 113.8317965, 'Palangka Raya', 'Kota Palangka Raya atau Palangkaraya adalah sebuah kota sekaligus merupakan ibu kota Provinsi Kalimantan Tengah. Dahulu dikenal dengan Palangkaraja (1957-1972). Kota ini memiliki luas wilayah 2.400 km² dan berpenduduk sebanyak 220.962 jiwa. Palangka Raya merupakan kota dengan luas wilayah terbesar di Indonesia. Sebagian wilayahnya masih berupa hutan, termasuk hutan lindung, konservasi alam serta Hutan Lindung Tangkiling.', 'http://localhost:8080/sig_indonesia/img/marker-blue.png'),
(22, -8.3431014, 115.3670791, 'Gunung Agung', 'Gunung Agung adalah gunung tertinggi di pulau Bali dengan ketinggian 3.031 mdpl. Gunung ini terletak di kecamatan Rendang, Kabupaten Karangasem - Bali. Gunung Agung adalah gunung berapi tipe stratovolcano, gunung ini memiliki kawah yang sangat besar dan sangat dalam yang kadang-kadang mengeluarkan asap dan uap air. Dari Pura Besakih gunung ini nampak dengan kerucut runcing sempurna, tetapi sebenarnya puncak gunung ini memanjang dan berakhir pada kawah yang melingkar dan lebar.', 'http://localhost:8080/sig_indonesia/img/marker-blue.png'),
(23, -7.9420836, 112.6728689, 'Gunung Bromo', 'Gunung Bromo (dari bahasa Sanskerta: Brahma, salah seorang Dewa Utama dalam agama Hindu), adalah sebuah gunung berapi aktif di Jawa Timur, Indonesia. Gunung ini memiliki ketinggian 2.329 meter di atas permukaan laut dan berada dalam empat wilayah kabupaten, yakni Kabupaten Probolinggo, Kabupaten Pasuruan, Kabupaten Lumajang, dan Kabupaten Malang. Gunung Bromo terkenal sebagai obyek wisata utama di Jawa Timur. Gunung Bromo mempunyai sebuah kawah dengan garis tengah ± 800 meter (utara-selatan) dan ± 600 meter (timur-barat). Sedangkan daerah bahayanya berupa lingkaran dengan jari-jari 4 km dari pusat kawah Bromo.', 'http://localhost:8080/sig_indonesia/img/marker-blue.png'),
(24, -8.1075316, 112.8523665, 'Gunung Semeru', 'Gunung Semeru merupakan gunung berapi tertinggi di Pulau Jawa, dengan puncaknya Mahameru, 3.676 meter dari permukaan laut (mdpl). Banyak sekali spot ? spot yang terkenal indahnya. Contohnya Oro ? oro Ombo, Danau Ranu Kumbolo dan Kalimati. Oro ? oro Ombo merupakan padang bunga yang sangat cantik. Kalau Danau Ranu Kumbolo terkenal dengan keindahan sunrise di pagi hari. Sedangkan kawasan Kalimati terkenal indah sekaligus unik karena pasirnya yang hitam.', 'http://localhost:8080/sig_indonesia/img/marker-blue.png'),
(25, -7.3191408, 107.6610084, 'Gunung Papandayan', 'Gunung Papandayan terletak di Cisurupan, Garut, Jawa Barat. Gunung ini mempunyai ketinggian 2.665 Mdpl. Papandayan mempunyai kawah yang masih aktif jadi bisa menghamburkan belerang kapan saja. Saat mendaki, Anda bisa menikmati pemandangan padang Edelweiss yang luar biasa cantik. Efek letusan dan pepohonan yang mengering juga akan membuat pendakian jadi lebih menarik. Karena keindahan Gunung Papandayan juga digunakan sebagai tempat foto pre wedding', 'http://localhost:8080/sig_indonesia/img/marker-blue.png'),
(26, -8.4108905, 116.3172605, 'Gunung Rinjani', 'Gunung yang merupakan gunung berapi kedua tertinggi di Indonesia dengan ketinggian 3.726 m dpl. Gunung Rinjani merupakan gunung favorit bagi pendaki Indonesia karena keindahan pemandangannya. Tempat yang sering dikunjungi adalah Segara Anak atau sering disebut segara anakan, sebuah danau terletak di ketinggian 2.000m dpl. Untuk mencapai lokasi ini kita bisa mendaki dari desa Senaru atau desa Sembalun Lawang.', 'http://localhost:8080/sig_indonesia/img/marker-blue.png'),
(27, -7.4549113, 110.4049803, 'Gunung Merbabu', 'Gunung Merbabu terletak di wilayah Magelang dan Boyolali dengan ketinggian 3.142 Mdpl. Merbabu adalah salah satu gunung terindah di Indonesia. Pendakian di gunung merbabu cukup populer, karena gunung merbabu memilik jalur pendakian yang tidak terlalu tinggi, tapi pemandangan yang tersaji sangatlah indah. Merbabu di kenal memiliki 7 buah puncak dengan 2 puncak tertinggi yaitu puncak Syarif ( 3.119 Mdpl)  dan Puncak Trianggulasi ( 3.142 Mdpl ). Gunung ini memiliki 5 buah kawah yaitu kawah Condrodimuko, kawah Kombang, Kendang, Rebab, dan kawah Sambernyowo.', 'http://localhost:8080/sig_indonesia/img/marker-blue.png'),
(28, -8.7685095, 121.6820202, 'Gunung Kelimutu', 'Gunung Kelimutu adalah gunung berapi yang terletak di Pulau Flores, Provinsi NTT, Indonesia. Lokasi gunung ini tepatnya di Desa Pemo, Kecamatan Kelimutu, Kabupaten Ende. Gunung ini memiliki tiga buah danau kawah di puncaknya. Danau ini dikenal dengan nama Danau Tiga Warna karena memiliki tiga warna yang berbeda, yaitu merah, biru, dan putih. Walaupun begitu, warna-warna tersebut selalu berubah-ubah seiring dengan perjalanan waktu.', 'http://localhost:8080/sig_indonesia/img/marker-blue.png'),
(29, -8.247521, 117.8510126, 'Gunung Tambora', 'Gunung Tambora atau Tomboro terletak di pulau Sumbawa tepatnya terletak di dua kabupaten, yaitu Kabupaten Dompu dan Bima, Provinsi Nusa Tenggara Barat. Keindahan alam Gunung Tambora sangat unik. Lebar kawah Gunung Tambora 7 km, keliling kawah 16 km, dan kedalaman kawah dari puncak sampai dasar kawah kedalaman 800m, sehingga kawah Gunung Tambora terkenal dengan The Greatest Crater in Indonesia ( Kawah Terbesar di Indonesia ). Kawah besar ini merupakan akibat dari adanya letusan terdahsyat di dunia terkenal dengan The Largest Volcanic Eruption in History.', 'http://localhost:8080/sig_indonesia/img/marker-blue.png'),
(30, -6.8862347, 107.0261866, 'Gunung Burangrang', 'Gunung Burangrang merupakan sebuah gunung api mati yang terdapat di pulau Jawa, Indonesia. Gunung Burangrang mempunyai ketinggian setinggi 2.064 meter. Gunung ini merupakan salah-satu sisa dari hasil letusan besar Gunung Sunda di Zaman Prasejarah. Gunung Burangrang bersebelahan dengan Gunung Sunda.', 'http://localhost:8080/sig_indonesia/img/marker-blue.png'),
(31, -7.3224113, 107.8249804, 'Gunung Cikuray', 'Gunung Cikuray adalah sebuah gunung yang terletak di Kabupaten Garut, Jawa Barat, Indonesia. Gunung Cikurai mempunyai ketinggian 2.821 meter di atas permukaan laut dan merupakan gunung tertinggi keempat di Jawa Barat setelah Gunung Gede. Gunung ini berada di perbatasan kecamatan Bayongbong, Cikajang, dan Dayeuh Manggung.', 'http://localhost:8080/sig_indonesia/img/marker-blue.png'),
(32, -6.8932448, 108.371647, 'Gunung Ceremai', 'Gunung Ceremai (seringkali secara salah kaprah dinamakan "Ciremai") adalah gunung berapi kerucut yang secara administratif termasuk dalam wilayah tiga kabupaten, yakni Kabupaten Cirebon, Kabupaten Kuningan dan Kabupaten Majalengka, Provinsi Jawa Barat. Posisi geografis puncaknya terletak pada 6° 53 30" LS dan 108° 24 00" BT, dengan ketinggian 3.078 m di atas permukaan laut. Gunung ini merupakan gunung tertinggi di Jawa Barat. Gunung ini memiliki kawah ganda. Kawah barat yang beradius 400 m terpotong oleh kawah timur yang beradius 600 m. Pada ketinggian sekitar 2.900 m dpl di lereng selatan terdapat bekas titik letusan yang dinamakan Gowa Walet.', 'http://localhost:8080/sig_indonesia/img/marker-blue.png'),
(33, -7.266578, 108.0366471, 'Gunung Galunggung', 'Gunung Galunggung merupakan gunung berapi dengan ketinggian 2.167 meter di atas permukaan laut, terletak sekitar 17 km dari pusat kota Tasikmalaya. Terdapat beberapa daya tarik wisata yang ditawarkan antara lain obyek wisata dan daya tarik wanawisata dengan areal seluas kurang lebih 120 hektaree di bawah pengelolaan Perum Perhutani. Obyek yang lainnya seluas kurang lebih 3 hektar berupa pemandian air panas (Cipanas) lengkap dengan fasilitas kolam renang, kamar mandi dan bak rendam air panas', 'http://localhost:8080/sig_indonesia/img/marker-blue.png'),
(34, 0.8092094, 127.3158237, 'Gunung Gamalama', 'Gunung Gamalama adalah sebuah gunung stratovolcano kerucut yang merupakan keseluruhan Pulau Ternate, Kepulauan Maluku, Indonesia. Pulau ini ada di pesisir barat Pulau Halmahera yang ada di bagian utara Kepulauan Maluku. Selama berabad-abad, Ternate adalah pusat benteng Portugis dan VOC Belanda untuk perdagangan rempah-rempah, yang telah mencatat aktivitas volkanik Gamalama. Gunung Gamalama mempunyai ketinggian 1.715 meter di atas permukaan laut. Gunung Gamalama ditutupi Hutan Montane pada ketinggian 1.200 - 1.500 m dan Hutan Ericaceous pada ketinggian di atas 1.500 m', 'http://localhost:8080/sig_indonesia/img/marker-blue.png'),
(35, -6.7876893, 106.9468391, 'Gunung Gede', 'Gunung Gede merupakan sebuah gunung yang berada di Pulau Jawa, Indonesia. Gunung Gede berada dalam ruang lingkup Taman Nasional Gede Pangrango, yang merupakan salah satu dari lima taman nasional yang pertama kali diumumkan di Indonesia pada tahun 1980. Gunung ini berada di wilayah tiga kabupaten yaitu Kabupaten Bogor, Cianjur dan Sukabumi, dengan ketinggian 1.000 - 3.000 m. dpl, dan berada pada lintang 106°51 - 107°02 BT dan 64°1 - 65°1 LS. Suhu rata-rata di puncak gunung Gede 18 °C dan di malam hari suhu puncak berkisar 5 °C, dengan curah hujan rata-rata 3.600 mm/tahun. Gerbang utama menuju gunung ini adalah dari Cibodas dan Cipanas.', 'http://localhost:8080/sig_indonesia/img/marker-blue.png'),
(36, -7.5406288, 110.4107044, 'Gunung Merapi', 'Gunung Merapi (ketinggian puncak 2.968 m dpl, per 2006) adalah gunung berapi di bagian tengah Pulau Jawa dan merupakan salah satu gunung api teraktif di Indonesia. Lereng sisi selatan berada dalam administrasi Kabupaten Sleman, Daerah Istimewa Yogyakarta, dan sisanya berada dalam wilayah Provinsi Jawa Tengah, yaitu Kabupaten Magelang di sisi barat, Kabupaten Boyolali di sisi utara dan timur, serta Kabupaten Klaten di sisi tenggara. Kawasan hutan di sekitar puncaknya menjadi kawasan Taman Nasional Gunung Merapi sejak tahun 2004.', 'http://localhost:8080/sig_indonesia/img/marker-blue.png'),
(37, -6.715969, 106.6986993, 'Gunung Salak', 'Gunung Salak merupakan kompleks gunung berapi yang terletak di selatan Jakarta, di Pulau Jawa. Kawasan rangkaian gunung ini termasuk ke dalam wilayah Kabupaten Sukabumi dan Kabupaten Bogor, Jawa Barat. Pengelolaan kawasan hutannya semula berada di bawah Perum Perhutani Kesatuan Pemangkuan Hutan (KPH) Bogor, tetapi sejak 2003 menjadi wilayah perluasan Taman Nasional Gunung Halimun, dan dikelola sebagai Taman Nasional Gunung Halimun-Salak. Gunung Salak berusia relatif tua sehingga memiliki beberapa puncak. dengan ketinggian puncak 2.211 m dari permukaan laut (dpl.).', 'http://localhost:8080/sig_indonesia/img/marker-blue.png'),
(38, 3.1697998, 98.3229931, 'Gunung Sinabung', 'adalah gunung api di Dataran Tinggi Karo, Kabupaten Karo, Sumatera Utara, Indonesia. Sinabung bersama Gunung Sibayak di dekatnya adalah dua gunung berapi aktif di Sumatera Utara dan menjadi puncak tertinggi ke 2 di provinsi itu. Ketinggian gunung ini adalah 2.451 meter.', 'http://localhost:8080/sig_indonesia/img/marker-blue.png'),
(39, -7.2412045, 109.1444034, 'Gunung Slamet', 'Gunung Slamet (3.428 meter dpl.) adalah sebuah gunung berapi kerucut yang terdapat di Pulau Jawa, Indonesia. Gunung Slamet terletak di antara 5 kabupaten, yaitu Kabupaten Brebes, Kabupaten Banyumas, Kabupaten Purbalingga, Kabupaten Tegal, dan Kabupaten Pemalang, Provinsi Jawa Tengah. Gunung Slamet merupakan gunung tertinggi di Jawa Tengah serta kedua tertinggi di Pulau Jawa setelah Gunung Semeru. Kawah IV merupakan kawah terakhir yang masih aktif sampai sekarang, dan terakhir aktif hingga pada level siaga medio-2009.', 'http://localhost:8080/sig_indonesia/img/marker-blue.png'),
(40, -4.0820307, 137.1160938, 'Gunung Jaya Wijaya', 'Puncak Jaya ialah sebuah puncak yang menjadi bagian dari Barisan Sudirman yang terdapat di Provinsi Papua, Indonesia. Puncak Jaya mempunyai ketinggian 4.884 m dan di sekitarnya terdapat gletser Carstensz, satu-satunya gletser tropika di Indonesia, yang kemungkinan besar segera akan lenyap akibat pemanasan global.', 'http://localhost:8080/sig_indonesia/img/marker-blue.png'),
(41, -6.7595942, 107.592271, 'Gunung Tangkuban Perahu', 'Tangkuban Parahu atau Gunung Tangkuban Perahu adalah salah satu gunung yang terletak di Provinsi Jawa Barat, Indonesia. Sekitar 20 km ke arah utara Kota Bandung, dengan rimbun pohon pinus dan hamparan kebun teh di sekitarnya, Gunung Tangkuban Perahu mempunyai ketinggian setinggi 2.084 meter. Bentuk gunung ini adalah Stratovulcano dengan pusat erupsi yang berpindah dari timur ke barat. Jenis batuan yang dikeluarkan melalui letusan kebanyakan adalah lava dan sulfur, mineral yang dikeluarkan adalah sulfur belerang, mineral yang dikeluarkan saat gunung tidak aktif adalah uap belerang. Daerah Gunung Tangkuban Perahu dikelola oleh Perum Perhutanan. Suhu rata-rata hariannya adalah 17 oC pada siang hari dan 2 oC pada malam hari.', 'http://localhost:8080/sig_indonesia/img/marker-blue.png'),
(42, -0.2273633, 130.3727316, 'Raja Ampat', 'Kepulauan Raja Ampat merupakan rangkaian empat gugusan pulau yang berdekatan dan berlokasi di barat bagian Kepala Burung (Vogelkoop) Pulau Papua. Secara administrasi, gugusan ini berada di bawah Kabupaten Raja Ampat, Provinsi Papua Barat. Kepulauan ini sekarang menjadi tujuan para penyelam yang tertarik akan keindahan pemandangan bawah lautnya. Empat gugusan pulau yang menjadi anggotanya dinamakan menurut empat pulau terbesarnya, yaitu Pulau Waigeo, Pulau Misool, Pulau Salawati, dan Pulau Batanta.', 'http://localhost:8080/sig_indonesia/img/marker-blue.png'),
(43, 1.6758483, 124.7206236, 'Taman Laut Bunaken', 'Indonesia sangat terkenal dengan keindahan wisata bawah lautnya salah satunya adalah wisata taman laut bunaken. Bunaken terletak di provinsi Sulawesi Utara. Dengan melakukan snorkeling di laut Bunaken, anda akan dimanjakan dengan keindahan terumbu karang dan ikan yang sangat indah. Karena keindahan alam bawah lautnya, maka dari itu bunaken masuk kedalam 10 tempat wisata terpopuler dan terbaik di Indonesia.', 'http://localhost:8080/sig_indonesia/img/marker-blue.png'),
(44, -8.5823354, 115.992795, 'Pulau Lombok', 'Pulau Lombok terletak di provinsi Nusa Tenggara Barat. Pulau Lombok merupakan kumpulan dari beberapa pulau kecil. Wisata pulau Lombok sebagian besar adalah wisata pantai. Ada pantai Senggigi yang terkenal dengan keindahan bawah lautnya.', 'http://localhost:8080/sig_indonesia/img/marker-blue.png'),
(45, -8.5888677, 119.3325474, 'Pulau Komodo', 'Komodo merupakan hewan yang masuk salah satu keajaiban dunia. Komodo hanya tinggal di pulau Komodo. Pulau komodo terletak di provinsi Nusa Tenggara Timur. Selain menikmati kehidupan binatang terlangka ini, anda juga bisa menikmati keindahan alam yang tak kalah menakjubkan.', 'http://localhost:8080/sig_indonesia/img/marker-blue.png'),
(46, -5.5634683, 123.9282367, 'Wakatobi', 'Wakatobi menjadi salah satu taman nasional yang mempunyai keindahan alam bawah laut yang tak kalah bagus dibandingkan Raja Ampat dan Bunaken. Bagi anda yang hobi menyelam, anda harus wajib mengunjungi Wakatobi. Waktobi terletak di provinsi Sulawesi Tenggara.', 'http://localhost:8080/sig_indonesia/img/marker-blue.png'),
(47, 1.04363, 96.9426033, 'Pulau Nias', 'Nias memiliki reputasi dunia dengan pesona lompat batu dan kegiatan selancar. Dinding batu setinggi 2 meter dapat dilompati oleh pemuda setempat dengan begitu mudahnya. Ini adalah suguhan atraksi di Nias yang terkenal, dapat Anda temukan di desa Bawomatauo. Tradisi lompat batu di Pulau Nias lahir dari kebiasaan berperang antardesa masyarakat Pulau Nias. Di desa Bawatomataluo dan Hilisimae, ada juga pertunjukan tari perang tradisional dimana para penarinya mengenakan kostum tradisional dengan bulu burung berwarna cerah yang diikatkan di kepala mereka.', 'http://localhost:8080/sig_indonesia/img/marker-blue.png'),
(48, -3.3171351, 114.5591929, 'Banjarmasin', 'Kota Banjarmasin adalah ibu kota provinsi Kalimantan Selatan, Indonesia serta kota terbesar dan terpadat di Kalimantan. Kota ini juga termasuk salah satu kota besar di Indonesia dan Kota terpadat di luar pulau Jawa. Banjarmasin yang dijuluki Kota Seribu Sungai ini memiliki wilayah seluas 72 km² yang wilayahnya merupakan delta atau kepulauan yang terdiri dari sekitar 25 buah pulau kecil (delta) yang dipisahkan oleh sungai-sungai diantaranya pulau Tatas, pulau Kelayan, pulau Rantauan Keliling, pulau Insan dan lain-lain. Berdasarkan data BPS Kota Banjarmasin tahun 2015, Banjarmasin memiliki penduduk sebanyak 675.440 jiwa dengan kepadatan 9.381 jiwa per km². Wilayah metropolitan Banjarmasin yaitu Banjar Bakula memiliki penduduk sekitar 1,9 juta jiwa.', 'http://localhost:8080/sig_indonesia/img/marker-blue.png'),
(49, -0.5013804, 117.0973125, 'Samarinda', 'Kota Samarinda merupakan ibu kota provinsi Kalimantan Timur, Indonesia serta salah satu kota terbesar di Kalimantan. Seluruh wilayah kota ini berbatasan langsung dengan Kabupaten Kutai Kartanegara. Kota Samarinda dapat dicapai dengan perjalanan darat, laut dan udara. Dengan Sungai Mahakam yang membelah di tengah Kota Samarinda, yang menjadi "gerbang" menuju pedalaman Kalimantan Timur. Kota ini memiliki luas wilayah 718 kilometer persegi dan berpenduduk 805.688 jiwa pada tahun 2013 (Badan Pusat Statistik Kota Samarinda), menjadikan kota ini berpenduduk terbesar di seluruh Kalimantan.', 'http://localhost:8080/sig_indonesia/img/marker-blue.png'),
(50, 2.7473878, 117.3263281, 'Tanjung Selor', 'Tanjung Selor merupakan Ibu Kota Provinsi Kalimantan Utara. Kota Tanjung Selor terletak di Kabupaten Bulungan yang sekaligus Ibu Kota Kabupaten Bulungan. Tanjung Selor memiliki luas wilayah 1.277,81 km² dan berdasarkan data BPS Kabupaten Bulungan jumlah penduduk sebanyak Tanjung Selor sebanyak 42.231 Orang pada tahun 2012 dengan rincian jumlah penduduk 22.488 laki-laki dan 19.743 perempuan dengan Angka Sex Ratio sebesar 113,90 persen.s', 'http://localhost:8080/sig_indonesia/img/marker-blue.png'),
(51, 1.4828624, 124.8006422, 'Manado', 'Kota Manado adalah ibu kota dari provinsi Sulawesi Utara. Kota Manado seringkali disebut sebagai Menado. Kota Manado berada di tepi pantai Laut Sulawesi persisnya di Teluk Manado. Taman Nasional Bunaken terletak tidak jauh dari pantai Kota Manado. Luas wilayah kota Manado adalah 157,3 km² dengan jumlah penduduk pada tahun 2010 sebesar 410.481.', 'http://localhost:8080/sig_indonesia/img/marker-blue.png'),
(52, -0.819027, 119.7321622, 'Palu', 'Palu adalah Ibukota Provinsi Sulawesi Tengah, Indonesia merupakan kota yang terletak di Sulawesi Tengah. Penduduk Kota Palu berjumlah 342.754 jiwa (2012) dengan luas kota sebesar 395,1 km².', 'http://localhost:8080/sig_indonesia/img/marker-blue.png'),
(53, -5.1225857, 119.391229, 'Makassar', 'Kota Makassar (Makassar: dari 1971 hingga 1999 secara resmi dikenal sebagai Ujung Pandang) adalah ibu kota provinsi Sulawesi Selatan. Makassar merupakan kota Internasional serta terbesar di kawasan Indonesia Timur dan pada masa lalu pernah menjadi ibukota Negara Indonesia Timur Provinsi Sulawesi. Dengan memiliki wilayah seluas 199,26 km² dan jumlah penduduk lebih dari 1,6 juta jiwa, kota ini berada di urutan kelima berpenduduk terbesar di Indonesia setelah Jakarta, Surabaya, Bandung dan Medan.', 'http://localhost:8080/sig_indonesia/img/marker-blue.png'),
(54, -3.9848755, 122.4670039, 'Kendari', 'Kendari adalah ibu kota Provinsi Sulawesi Tenggara, Indonesia. Kendari diresmikan sebagai kotamadya (kini kota) dengan UU RI No. 6 Tahun 1995 tanggal 27 September 1995. Kota ini memiliki luas 296,00 km² (29.600 Ha) dan berpenduduk 200.474 jiwa (2000).', 'http://localhost:8080/sig_indonesia/img/marker-blue.png'),
(55, -2.7059004, 118.8782086, 'Mamuju', 'Kabupaten Mamuju adalah salah satu Daerah Tingkat II di provinsi Sulawesi Barat, Indonesia. Luas wilayah kabupaten ini sebelum dimekarkan adalah 11.057,81 km². Jumlah penduduk di kabupaten ini sebanyak 231.384 jiwa. Ibukotanya adalah Mamuju.', 'http://localhost:8080/sig_indonesia/img/marker-blue.png'),
(56, 0.6763629, 121.2352848, 'Gorontalo', 'Gorontalo adalah sebuah provinsi di Indonesia. Ibukota Provinsi Gorontalo adalah Kota Gorontalo (sering disebut juga Kota Hulontalo) yang terkenal dengan julukan "Kota Serambi Madinah".Provinsi Gorontalo terletak di Pulau Sulawesi bagian utara atau di bagian barat dari Provinsi Sulawesi Utara. Luas wilayah provinsi ini 12.435,00 km² dengan jumlah penduduk sebanyak 1.097.990 jiwa, dengan tingkat kepadatan penduduk 88 jiwa/km².', 'http://localhost:8080/sig_indonesia/img/marker-blue.png'),
(57, -3.7045887, 128.1147532, 'Ambon', 'Kota Ambon atau Amboina atau Ambonese (kadang dieja sebagai Ambong atau Ambuni) adalah sebuah kota dan sekaligus ibu kota dari provinsi Maluku, Indonesia. Kota Ambon memiliki luas wilayah seluas 377 km² dengan jumlah penduduk pada tahun 2010 sebesar 331.254 jiwa.', 'http://localhost:8080/sig_indonesia/img/marker-blue.png'),
(58, 0.7334813, 127.5508325, 'Sofifi', 'Sofifi adalah ibu kota baru Provinsi Maluku Utara sejak 4 Agustus 2010.[1] Kedudukannya sebagai ibu kota provinsi sudah di rencanakan sejak pecahnya Maluku Utara dari Maluku tahun 1999, Ternate menjadi ibu kota sementara provinsi ke-27 Indonesia. Sofifi memiliki jumlah penduduk 36.197 jiwa.', 'http://localhost:8080/sig_indonesia/img/marker-blue.png'),
(59, -2.5649646, 140.6109867, 'Jayapura', 'Kota Jayapura adalah ibu kota provinsi Papua, Indonesia. Kota ini merupakan ibu kota provinsi yang terletak paling timur di Indonesia. Kota ini terletak di teluk Jayapura. Pada tahun 2010 Jayapura memiliki jumlah penduduk sebanyak 256.705 jiwa.', 'http://localhost:8080/sig_indonesia/img/marker-blue.png'),
(60, -0.8641952, 134.0040575, 'Manokwari', 'Manokwari adalah ibu kota Provinsi Papua Barat, Indonesia. Manokwari juga merupakan ibu kota Kabupaten Manokwari. Kota ini memiliki luas wilayah 1.556,94 km² dan berpenduduk sebanyak kurang lebih 99.488 jiwa.', 'http://localhost:8080/sig_indonesia/img/marker-blue.png'),
(61, 2.6114159, 98.5557643, 'Danau Toba', 'Danau Toba adalah sebuah danau vulkanik dengan ukuran panjang 100 kilometer dan lebar 30 kilometer yang terletak di Provinsi Sumatera Utara, Indonesia. Danau ini merupakan danau terbesar di Indonesia dan Asia Tenggara. Di tengah danau ini terdapat sebuah pulau vulkanik bernama Pulau Samosir.', 'http://localhost:8080/sig_indonesia/img/marker-blue.png'),
(62, -5.9205126, 105.8683233, 'Selat Sunda', 'Selat Sunda merupakan selat yang menghubungkan pulau Jawa dan Sumatera di Indonesia, serta menghubungkan Laut Jawa dengan Samudera Hindia. Pada titik tersempit, lebar selat Sunda hanya sekitar 30 km. Beberapa pulau kecil terletak di selat ini, diantaranya pulau vulkanik Krakatau.', 'http://localhost:8080/sig_indonesia/img/marker-blue.png'),
(63, -5.0353108, 111.5658721, 'Laut Jawa', 'Laut Jawa adalah perairan dangkal dengan luas kira-kira 310.000 km2 di antara Pulau Kalimantan, Jawa, Sumatera, dan Sulawesi di gugusan kepulauan Indonesia. Laut ini relatif muda, terbentuk pada Zaman Es terakhir (sekitar 12.000 tahun Sebelum Masehi) ketika dua sistem sungai bersatu. Di barat lautnya, Selat Karimata yang menghubungkannya dengan Laut China Selatan.', 'http://localhost:8080/sig_indonesia/img/marker-blue.png'),
(64, -10.1750634, 127.4581843, 'Laut Arafura', 'Laut Arafura atau Laut Arafuru adalah wilayah perairan yang berada di antara Australia dan Pulau Papua, di Samudra Pasifik. Luasnya adalah 650.000 km² dan kedalaman maksimalnya adalah 3,68 km.', 'http://localhost:8080/sig_indonesia/img/marker-blue.png'),
(65, -4.8386911, 122.2926895, 'Laut Banda', 'Laut Banda adalah sebuah laut yang terletak di Kepulauan Maluku, Indonesia. Laut berukuran 500x1.000 km ini terpisah dari Samudra Pasifik oleh beratus-ratus pulau, serta Laut Halmahera dan Seram.', 'http://localhost:8080/sig_indonesia/img/marker-blue.png'),
(66, -7.116941, 117.7846229, 'Laut Flores', 'Laut Flores adalah laut yang terdapat di sebelah utara Pulau Flores. Laut ini juga menjadi batas alami antara Provinsi Nusa Tenggara Barat dengan Provinsi Sulawesi Selatan. Di sebelah utara Laut Flores terdapat gugusan pulau-pulau kecil, diantaranya Kepulauan Bonerate dan Pulau Kalaotoa. Laut Flores memiliki kedalaman hingga 5.123 meter. Laut Flores mencakup 93.000 mil persegi (240.000 km²) air di Indonesia. Laut Flores dari dinamai Pulau Flores.', 'http://localhost:8080/sig_indonesia/img/marker-blue.png'),
(67, 1.2921131, 123.6897876, 'Laut Maluku', 'ILaut Maluku terletak di barat Samudra Pasifik yang terletak di dekat Provinsi Maluku, Indonesia. Laut ini membatasi Laut Sulawesi di utara dan Laut Banda di selatan. Pulau pulau yang membatasi laut ini adalah kepulauan Indonesia seperti Halmahera, Seram, Buru, dan Sulawesi (Celebes).', 'http://localhost:8080/sig_indonesia/img/marker-blue.png'),
(68, -9.5871104, 119.5086472, 'Laut Sawu', 'Laut Sawu adalah laut yang terdapat di antara Pulau Sumba, Pulau Sawu, Pulau Rote, Pulau Timor, dan Pulau Flores.Secara administratif, Laut Sawu termasuk wilayah Provinsi Nusa Tenggara Timur. Laut Sawu memiliki kedalaman hingga 3.497 meter dan mencakup area seluas sekitar 3,5 juta hektare.Laut ini termasuk ke dalam cagar alam laut (marine protected area) sejak awal 2009, dan merupakan bagian dari Segitiga Terumbu Karang. Penetapan ini berarti eksploitasi di laut ini harus mendapatkan izin dari pemerintah setempat; selain berdampak pada kehidupan 151 desa nelayan dari 10 kabupaten dan secara langsung akan mengubah cara hidup sekitar 25.625 keluarga.Paling tidak terdapat 500 jenis koral dan 300 jenis ikan menghuni perairan cagar alam terluas di wilayah Segitiga Koral ini. Selain itu, Laut Sawu menjadi bagian dari jalur migrasi 14 jenis Cetacea (termasuk paus biru dan paus sperma/lodan), dan empat dari tujuh jenis penyu laut (penyu hijau, penyu sisik, penyu lekang, dan penyu belimbing).Laut ini masih menjadi ajang penangkapan ikan dan eksplotasi terumbu karang yang ilegal dan merusak, seperti penggunaan bom dan sianida. Di sisi lain, usaha konservasi dan pengawasan mengalami keterbatasan sumber daya.', 'http://localhost:8080/sig_indonesia/img/marker-blue.png'),
(69, -3.215393, 127.6801016, 'Laut Seram', 'Laut Seram adalah salah satu dari beberapa laut kecil di kepulauan Indonesia. Laut ini merupakan bagian dari Samudra Pasifik dengan luas kira-kira 12.000 kilometer persegi terletak di antara Buru dan Seram. Laut Seram juga merupakan habitat untuk beberapa jenis goby tropis dan ikan lain. Seperti banyak laut kecil yang lain di Indonesia, laut ini berbatu dan memiliki aktivitas tektonik yang sangat aktif.', 'http://localhost:8080/sig_indonesia/img/marker-blue.png'),
(70, 4.3234897, 116.9216831, 'Laut Sulawesi', 'Laut Sulawesi di barat Samudra Pasifik dibatasi oleh Kepulauan Sulu, Laut Sulu, dan Pulau Mindanao, Filipina, di utara, di timur oleh rantai Kepulauan Sangihe, di selatan oleh Sulawesi, dan di barat oleh Kalimantan, Indonesia . Laut ini berbentuk basin besar, dan kedalamnya mencapai 6.200 m. Memanjang 420 mil (675 km) utara-selatan dengan 520 mil (837 km) timur-barat dan wilayah permukaan totalnya 110.000 mil persegi (280.000 km persegi). Laut ini membuka ke barat daya melalui Selat Makassar ke Laut Jawa.', 'http://localhost:8080/sig_indonesia/img/marker-blue.png'),
(71, -12.4422337, 122.7635186, 'Laut Timor', 'Laut Timor (Bahasa Portugis: Mar de Timor) adalah perpanjangan Samudera Hindia yang terletak antara pulau Timor, kini terbagi antara Indonesia dan Timor Leste, dan Teritorial Utara Australia. Di timur berbatasan dengan Laut Arafura, secara teknis perpanjangan Samudera Pasifik. Laut Timor memiliki 2 teluk kecil di pesisir Astralia utara, Teluk Joseph Bonaparte dan Teluk van Diemen. Kota Australia Darwin ialah satu-satunya kota besar yang terletak di tepi laut Timor.Laut ini memiliki luas 480 km (300 mil), meliputi darah sekitar 610.000 km persegi (235.000 mil persegi). Titik terdalamnya ialah Palung Timor di utara , yang mencapai kedalaman 3.300 m (10.800 kaki). Bagian lainnya lebih dangkal, dengan rata-rata kedalaman yang kurang dari 200 m (650 kaki). Merupakan tempat utama untuk badai tropis dan topan.', 'http://localhost:8080/sig_indonesia/img/marker-blue.png');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `data`
--
ALTER TABLE `data`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `data`
--
ALTER TABLE `data`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=72;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
